name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  api_key:
    required: true
    description: 'API key for IP lambda'
  endpoint_url:
    required: true
    description: 'IP lambda endpoint url'
runs:
  using: 'node20'
  main: 'dist/index.js'
